// *******************************************************
//                                                        
//    Copyright (C) Microsoft. All rights reserved.       
//                                                        
// *******************************************************

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToAssociationChange(Zentity.Administration.AssociationChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToChangeSet(Zentity.Administration.ChangeSet)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToDataModelModuleChange(Zentity.Administration.DataModelModuleChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToNavigationPropertyChange(Zentity.Administration.NavigationPropertyChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToOperation(Zentity.Administration.Operation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToPredicateChange(Zentity.Administration.PredicateChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToPropertyChange(Zentity.Administration.PropertyChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToRelationshipChange(Zentity.Administration.RelationshipChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToResourceChange(Zentity.Administration.ResourceChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToResourcePropertyChange(Zentity.Administration.ResourcePropertyChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToResourceTypeChange(Zentity.Administration.ResourceTypeChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToScalarPropertyChange(Zentity.Administration.ScalarPropertyChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Zentity.Administration.AdministrationContext.#AddToRelationshipPropertyChange(Zentity.Administration.RelationshipPropertyChange)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.DataModel.#GetResourceItemCount(Zentity.Core.ZentityContext,System.Collections.Generic.IEnumerable`1<System.String>,System.Int32&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.DataModel.#GetSynchronizedModelAndMappings(Zentity.Core.DataModel&,Zentity.Core.TableMappingCollection&,System.Collections.Generic.Dictionary`2<System.Guid,System.String>&,System.Collections.Generic.Dictionary`2<System.Guid,System.Int32>&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.DataModel.#Synchronize()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.ResourceType.#Update(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.Utilities.#PrepareCommand(System.Data.SqlClient.SqlConnection,System.Data.SqlClient.SqlTransaction,System.Int32,System.String,System.Data.CommandType,System.Data.SqlClient.SqlParameter[],System.Data.SqlClient.SqlCommand)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.ZentityContext+SavingChangesHandler.#ValidateOneToXxxRelationshipDeletions()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2100:Review SQL queries for security vulnerabilities", Scope = "member", Target = "Zentity.Core.DataModel+DataModelLoader.#Refresh(Zentity.Core.DataModel,System.Data.SqlClient.SqlConnection)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "Zentity.Core.DataModel.#GenerateExtensionsAssembly(System.String,System.Boolean,System.String[],System.String[],System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "Zentity.Core.DataModel.#GenerateFlattenedExtensionsAssembly(System.String,System.Boolean,System.String[],System.String[],System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "Zentity.Core.DataModel.#ValidateCSharpIdentifiers()")]
