//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Services.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Services.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.dll.
        /// </summary>
        internal static string AssemblyExtension {
            get {
                return ResourceManager.GetString("AssemblyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.cxml.
        /// </summary>
        internal static string CxmlExtension {
            get {
                return ResourceManager.GetString("CxmlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel.
        /// </summary>
        internal static string DataModelName {
            get {
                return ResourceManager.GetString("DataModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dzi.
        /// </summary>
        internal static string DeepZoomImageFileExtension {
            get {
                return ResourceManager.GetString("DeepZoomImageFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepZoomImages.
        /// </summary>
        internal static string DeepZoomImageFolderName {
            get {
                return ResourceManager.GetString("DeepZoomImageFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepZoomImages/Default.dzi.
        /// </summary>
        internal static string DefaultDzi {
            get {
                return ResourceManager.GetString("DefaultDzi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;style&gt;body { margin: 0px; font-family:Segoe UI, Arial Unicode MS, Arial, Sans-Serif; } p.header { font-size: 80px; color: white; background: #454545; width: 100%; filter: alpha(opacity=50); padding: 5px 20px; } p.footer { position:absolute; bottom:0; font-size: 30px; color: white; background: #AAA; width: 100%; padding: 10px 20px; } div { position:absolute; top:0; left:0; width:100%; height:100%; border:5px inset #aaaaaa; }&lt;/style&gt;&lt;/head&gt;&lt;body&gt;&lt;div&gt;&lt;p class=&quot;header&quot;&gt;{name}&lt;/p&gt;&lt;p class=&quot;footer&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultHtmlTemplate {
            get {
                return ResourceManager.GetString("DefaultHtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dll.
        /// </summary>
        internal static string DllExtension {
            get {
                return ResourceManager.GetString("DllExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dzc.
        /// </summary>
        internal static string DzcExtension {
            get {
                return ResourceManager.GetString("DzcExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .dzi.
        /// </summary>
        internal static string DziExtension {
            get {
                return ResourceManager.GetString("DziExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description,Tags,Name,Href,Files.
        /// </summary>
        internal static string ExcludedProperties {
            get {
                return ResourceManager.GetString("ExcludedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _files.
        /// </summary>
        internal static string FilesExtension {
            get {
                return ResourceManager.GetString("FilesExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cxml?Id=EQ..
        /// </summary>
        internal static string IdQueryString {
            get {
                return ResourceManager.GetString("IdQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image_{0}.{1}.
        /// </summary>
        internal static string ImageFileNameFormat {
            get {
                return ResourceManager.GetString("ImageFileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/bmp,image/gif,image/jpeg,image/png,image/tiff.
        /// </summary>
        internal static string ImageMimeTypes {
            get {
                return ResourceManager.GetString("ImageMimeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.Metadata.
        /// </summary>
        internal static string MetadataDllName {
            get {
                return ResourceManager.GetString("MetadataDllName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string MethodName_Load {
            get {
                return ResourceManager.GetString("MethodName_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OfType.
        /// </summary>
        internal static string MethodName_OfType {
            get {
                return ResourceManager.GetString("MethodName_OfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where.
        /// </summary>
        internal static string MethodName_Where {
            get {
                return ResourceManager.GetString("MethodName_Where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string MimeTypeSplitChar {
            get {
                return ResourceManager.GetString("MimeTypeSplitChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../.
        /// </summary>
        internal static string ParentDirectory {
            get {
                return ResourceManager.GetString("ParentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .cxml.
        /// </summary>
        internal static string PivotCollectionFileExtension {
            get {
                return ResourceManager.GetString("PivotCollectionFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/livelabs/pivot/collection/2009.
        /// </summary>
        internal static string PivotCollectionSchemaNamespace {
            get {
                return ResourceManager.GetString("PivotCollectionSchemaNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string ResourceName {
            get {
                return ResourceManager.GetString("ResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ResourcesName {
            get {
                return ResourceManager.GetString("ResourcesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string ResourceTypeFullNameFormat {
            get {
                return ResourceManager.GetString("ResourceTypeFullNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        internal static string ResourceTypeName {
            get {
                return ResourceManager.GetString("ResourceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.Core.
        /// </summary>
        internal static string ZentityCore {
            get {
                return ResourceManager.GetString("ZentityCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .zip.
        /// </summary>
        internal static string ZipExtension {
            get {
                return ResourceManager.GetString("ZipExtension", resourceCulture);
            }
        }
    }
}
