//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Security.Authorization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Security.Authorization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to authorize the resource(s). See inner exception for more details..
        /// </summary>
        internal static string AuthorizeException {
            get {
                return ResourceManager.GetString("AuthorizeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have access to create resource..
        /// </summary>
        internal static string CreateAccessDeniedException {
            get {
                return ResourceManager.GetString("CreateAccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have access to delete resource..
        /// </summary>
        internal static string DeleteAccessDeniedException {
            get {
                return ResourceManager.GetString("DeleteAccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to grant rights possibly because of incorrect input. See inner exception for more details..
        /// </summary>
        internal static string GrantAuthorizationException {
            get {
                return ResourceManager.GetString("GrantAuthorizationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not valid..
        /// </summary>
        internal static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token or AuthorizingPredicateUri can not be null..
        /// </summary>
        internal static string NullTokenOrUriException {
            get {
                return ResourceManager.GetString("NullTokenOrUriException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to revoke rights possibly because of incorrect input. See inner exception for more details..
        /// </summary>
        internal static string RevokeAuthorizationException {
            get {
                return ResourceManager.GetString("RevokeAuthorizationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find AuthenticatedToken in Thread Local Storage..
        /// </summary>
        internal static string TokenUnavailableInTLS {
            get {
                return ResourceManager.GetString("TokenUnavailableInTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not have access to update resource..
        /// </summary>
        internal static string UpdateAccessDeniedException {
            get {
                return ResourceManager.GetString("UpdateAccessDeniedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify information possibly because of incorrect input. See inner exception for more details..
        /// </summary>
        internal static string VerifyAuthorizationException {
            get {
                return ResourceManager.GetString("VerifyAuthorizationException", resourceCulture);
            }
        }
    }
}
