//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.SchWorksAndAuthArtifactGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.SchWorksAndAuthArtifactGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidated.msl.
        /// </summary>
        internal static string ConsolidatedMsl {
            get {
                return ResourceManager.GetString("ConsolidatedMsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidated.ssdl.
        /// </summary>
        internal static string ConsolidatedSsdl {
            get {
                return ResourceManager.GetString("ConsolidatedSsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtendedCore.csdl.
        /// </summary>
        internal static string ExtendedCoreCsdl {
            get {
                return ResourceManager.GetString("ExtendedCoreCsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csdl.
        /// </summary>
        internal static string FileExtensionCsdl {
            get {
                return ResourceManager.GetString("FileExtensionCsdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.ScholarlyWorks.
        /// </summary>
        internal static string ScholarlyWorksAssembly {
            get {
                return ResourceManager.GetString("ScholarlyWorksAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.ScholarlyWorksAuthorization.
        /// </summary>
        internal static string ScholarlyWorksAuthorizationNamespace {
            get {
                return ResourceManager.GetString("ScholarlyWorksAuthorizationNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.Security.Authorization.
        /// </summary>
        internal static string SecurityAuthorizationAssembly {
            get {
                return ResourceManager.GetString("SecurityAuthorizationAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZentityContext.
        /// </summary>
        internal static string ZentityContext {
            get {
                return ResourceManager.GetString("ZentityContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity.Core.
        /// </summary>
        internal static string ZentityCore {
            get {
                return ResourceManager.GetString("ZentityCore", resourceCulture);
            }
        }
    }
}
