//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Services.Windows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Services.Windows.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages in broker queue are exhausted. Notification service will go into sleep mode for : {0} ms..
        /// </summary>
        internal static string BrokerQueueExhausted {
            get {
                return ResourceManager.GetString("BrokerQueueExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while trying to add the broker message to internal queue..
        /// </summary>
        internal static string ExceptionAddingBrokerMessageToQueue {
            get {
                return ResourceManager.GetString("ExceptionAddingBrokerMessageToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while calling stored procedure \&quot;Core.FetchMessage\&quot;. Please check the exception details for more information..
        /// </summary>
        internal static string ExceptionCallingStoredProcedure {
            get {
                return ResourceManager.GetString("ExceptionCallingStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while creating the publishing service proxy. Please check the exception details for more information..
        /// </summary>
        internal static string ExceptionCreatingPublishingServiceProxy {
            get {
                return ResourceManager.GetString("ExceptionCreatingPublishingServiceProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured in the worker thread of Worker class. Please check the exception details for more information..
        /// </summary>
        internal static string ExceptionInWorkerThread {
            get {
                return ResourceManager.GetString("ExceptionInWorkerThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while message parsing. Please check the exception details for more information..
        /// </summary>
        internal static string ExceptionParsingMessage {
            get {
                return ResourceManager.GetString("ExceptionParsingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown while pushing message. ResourceChangeMessage count : {0}.
        /// </summary>
        internal static string ExceptionPushingMessage {
            get {
                return ResourceManager.GetString("ExceptionPushingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown by the publishing service. Please check the exception details for more information.\nNotification service will retry in {0} minutes..
        /// </summary>
        internal static string ExceptionThrownByPublishingService {
            get {
                return ResourceManager.GetString("ExceptionThrownByPublishingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched messages from SQL Broker queue..
        /// </summary>
        internal static string FetchedMessagesFromSqlBroker {
            get {
                return ResourceManager.GetString("FetchedMessagesFromSqlBroker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching messages from SQL Broker queue. Query : {0}.
        /// </summary>
        internal static string FetchingMessagesFromSqlBrokerQueue {
            get {
                return ResourceManager.GetString("FetchingMessagesFromSqlBrokerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages sent to publishing service. Resource Type : {0}. Message Count : {1}.
        /// </summary>
        internal static string MessagesSentToPublishingService {
            get {
                return ResourceManager.GetString("MessagesSentToPublishingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed the message from the internal queue to processed message list. ResourceChangeMessage added : {0}.
        /// </summary>
        internal static string ParsedMessageInInternalQueue {
            get {
                return ResourceManager.GetString("ParsedMessageInInternalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing the message from internal queue. Raw Messages in Queue : {0}.
        /// </summary>
        internal static string ParsingMessageInInternalQueue {
            get {
                return ResourceManager.GetString("ParsingMessageInInternalQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Service is busy. Notification service will go into sleep mode for : {0} seconds..
        /// </summary>
        internal static string PublishingServiceBusyGoingToSleep {
            get {
                return ResourceManager.GetString("PublishingServiceBusyGoingToSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Service is busy processing collection for \&apos;{0}\&apos;. Messages for this resource type will not be sent to publishing service..
        /// </summary>
        internal static string PublishingServiceBusyMessagesWillNotBeSent {
            get {
                return ResourceManager.GetString("PublishingServiceBusyMessagesWillNotBeSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publishing service host endpoint was unavailable. Timeout period has expired..
        /// </summary>
        internal static string PublishingServiceEndpointUnavailableAfterTimeout {
            get {
                return ResourceManager.GetString("PublishingServiceEndpointUnavailableAfterTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publishing service host endpoint was unavailable. Please check if the publishing service is started and the enpoint address is correct.\nNotification service will retry in {0} minutes..
        /// </summary>
        internal static string PublishingServiceEndpointUnavailableWithSuggestion {
            get {
                return ResourceManager.GetString("PublishingServiceEndpointUnavailableWithSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushed messages from processed message list to publishing service..
        /// </summary>
        internal static string PushedMessagesFromProcessedListToPublishingService {
            get {
                return ResourceManager.GetString("PushedMessagesFromProcessedListToPublishingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing all messages from processed message list to publishing service. ResourceChangeMessage count : {0}.
        /// </summary>
        internal static string PushingMessagesFromProcessedListToPublishingService {
            get {
                return ResourceManager.GetString("PushingMessagesFromProcessedListToPublishingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message from SQL Broker queue : Message Length (bytes) : {0}.
        /// </summary>
        internal static string ReceivedMessagesFromSqlBrokerQueue {
            get {
                return ResourceManager.GetString("ReceivedMessagesFromSqlBrokerQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Count : {0}.
        /// </summary>
        internal static string RetryCount {
            get {
                return ResourceManager.GetString("RetryCount", resourceCulture);
            }
        }
    }
}
