#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Services.Windows
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Zentity")]
	public partial class ZentityAdministrationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChangeMessageRecovery(ChangeMessageRecovery instance);
    partial void UpdateChangeMessageRecovery(ChangeMessageRecovery instance);
    partial void DeleteChangeMessageRecovery(ChangeMessageRecovery instance);
    partial void InsertMessageQueueRecovery(MessageQueueRecovery instance);
    partial void UpdateMessageQueueRecovery(MessageQueueRecovery instance);
    partial void DeleteMessageQueueRecovery(MessageQueueRecovery instance);
    #endregion
		
		public ZentityAdministrationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZentityAdministrationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZentityAdministrationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZentityAdministrationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChangeMessageRecovery> ChangeMessageRecoveries
		{
			get
			{
				return this.GetTable<ChangeMessageRecovery>();
			}
		}
		
		public System.Data.Linq.Table<MessageQueueRecovery> MessageQueueRecoveries
		{
			get
			{
				return this.GetTable<MessageQueueRecovery>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Administration.ChangeMessageRecovery")]
	public partial class ChangeMessageRecovery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _ResourceId;
		
		private System.Guid _ResourceTypeId;
		
		private string _DataModelNamespace;
		
		private string _ResourceTypeName;
		
		private short _ChangeType;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private System.Nullable<System.DateTime> _DateModified;
		
		private System.DateTime _DateTimeStamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnResourceIdChanging(System.Guid value);
    partial void OnResourceIdChanged();
    partial void OnResourceTypeIdChanging(System.Guid value);
    partial void OnResourceTypeIdChanged();
    partial void OnDataModelNamespaceChanging(string value);
    partial void OnDataModelNamespaceChanged();
    partial void OnResourceTypeNameChanging(string value);
    partial void OnResourceTypeNameChanged();
    partial void OnChangeTypeChanging(short value);
    partial void OnChangeTypeChanged();
    partial void OnDateAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateAddedChanged();
    partial void OnDateModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateModifiedChanged();
    partial void OnDateTimeStampChanging(System.DateTime value);
    partial void OnDateTimeStampChanged();
    #endregion
		
		public ChangeMessageRecovery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ResourceId
		{
			get
			{
				return this._ResourceId;
			}
			set
			{
				if ((this._ResourceId != value))
				{
					this.OnResourceIdChanging(value);
					this.SendPropertyChanging();
					this._ResourceId = value;
					this.SendPropertyChanged("ResourceId");
					this.OnResourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceTypeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ResourceTypeId
		{
			get
			{
				return this._ResourceTypeId;
			}
			set
			{
				if ((this._ResourceTypeId != value))
				{
					this.OnResourceTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ResourceTypeId = value;
					this.SendPropertyChanged("ResourceTypeId");
					this.OnResourceTypeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataModelNamespace", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string DataModelNamespace
		{
			get
			{
				return this._DataModelNamespace;
			}
			set
			{
				if ((this._DataModelNamespace != value))
				{
					this.OnDataModelNamespaceChanging(value);
					this.SendPropertyChanging();
					this._DataModelNamespace = value;
					this.SendPropertyChanged("DataModelNamespace");
					this.OnDataModelNamespaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResourceTypeName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ResourceTypeName
		{
			get
			{
				return this._ResourceTypeName;
			}
			set
			{
				if ((this._ResourceTypeName != value))
				{
					this.OnResourceTypeNameChanging(value);
					this.SendPropertyChanging();
					this._ResourceTypeName = value;
					this.SendPropertyChanged("ResourceTypeName");
					this.OnResourceTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeType", DbType="SmallInt NOT NULL")]
		public short ChangeType
		{
			get
			{
				return this._ChangeType;
			}
			set
			{
				if ((this._ChangeType != value))
				{
					this.OnChangeTypeChanging(value);
					this.SendPropertyChanging();
					this._ChangeType = value;
					this.SendPropertyChanged("ChangeType");
					this.OnChangeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateModified", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DateModified
		{
			get
			{
				return this._DateModified;
			}
			set
			{
				if ((this._DateModified != value))
				{
					this.OnDateModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateModified = value;
					this.SendPropertyChanged("DateModified");
					this.OnDateModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime2 NOT NULL", IsDbGenerated=true)]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this.OnDateTimeStampChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStamp = value;
					this.SendPropertyChanged("DateTimeStamp");
					this.OnDateTimeStampChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Administration.MessageQueueRecovery")]
	public partial class MessageQueueRecovery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.DateTime _DateTimeStamp;
		
		private string _RawMessage;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnDateTimeStampChanging(System.DateTime value);
    partial void OnDateTimeStampChanged();
    partial void OnRawMessageChanging(string value);
    partial void OnRawMessageChanged();
    #endregion
		
		public MessageQueueRecovery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStamp", DbType="DateTime2 NOT NULL", IsDbGenerated=true)]
		public System.DateTime DateTimeStamp
		{
			get
			{
				return this._DateTimeStamp;
			}
			set
			{
				if ((this._DateTimeStamp != value))
				{
					this.OnDateTimeStampChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStamp = value;
					this.SendPropertyChanged("DateTimeStamp");
					this.OnDateTimeStampChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RawMessage", DbType="NVarChar(MAX)")]
		public string RawMessage
		{
			get
			{
				return this._RawMessage;
			}
			set
			{
				if ((this._RawMessage != value))
				{
					this.OnRawMessageChanging(value);
					this.SendPropertyChanging();
					this._RawMessage = value;
					this.SendPropertyChanged("RawMessage");
					this.OnRawMessageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
