//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum.
        /// </summary>
        internal static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 1 FROM [Core].[Resource] WITH(NOLOCK) 
        ///WHERE [Id] = @Id AND [ResourceTypeId] IN 
        ///(SELECT [Id] FROM [Core].[GetDerivedTypes](&apos;94c567f8-b3eb-4ccb-9bf1-fc88970f78d7&apos;)).
        /// </summary>
        internal static string CmdFileExists {
            get {
                return ResourceManager.GetString("CmdFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT @PathName = Content.PathName(), 
        ///@TransactionContext = GET_FILESTREAM_TRANSACTION_CONTEXT() 
        ///FROM [Core].[Content] WITH (ROWLOCK) 
        ///WHERE [ResourceId] = @Id;.
        /// </summary>
        internal static string CmdGetPathNameAndTransactionToken {
            get {
                return ResourceManager.GetString("CmdGetPathNameAndTransactionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout.
        /// </summary>
        internal static string Command_Timeout {
            get {
                return ResourceManager.GetString("Command_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout={0}.
        /// </summary>
        internal static string CommandTimeoutFormat {
            get {
                return ResourceManager.GetString("CommandTimeoutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigName.
        /// </summary>
        internal static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigValue.
        /// </summary>
        internal static string ConfigValue {
            get {
                return ResourceManager.GetString("ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.GetConfigurationValue.
        /// </summary>
        internal static string Core_GetConfigurationValue {
            get {
                return ResourceManager.GetString("Core_GetConfigurationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.GetServerProperty.
        /// </summary>
        internal static string Core_GetServerProperty {
            get {
                return ResourceManager.GetString("Core_GetServerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.ValidateOneToXxxDeletion.
        /// </summary>
        internal static string Core_ValidateOneToXxxDeletion {
            get {
                return ResourceManager.GetString("Core_ValidateOneToXxxDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CsvDeletedRelationshipIds.
        /// </summary>
        internal static string CsvDeletedRelationshipIds {
            get {
                return ResourceManager.GetString("CsvDeletedRelationshipIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CsvDeletedResourceIds.
        /// </summary>
        internal static string CsvDeletedResourceIds {
            get {
                return ResourceManager.GetString("CsvDeletedResourceIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateModified.
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File resource could not be saved.
        /// </summary>
        internal static string FileCannotBeSaved {
            get {
                return ResourceManager.GetString("FileCannotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content stream could not be returned for the File with an identity of {0} : {1}.
        /// </summary>
        internal static string FileContentNotStreamed {
            get {
                return ResourceManager.GetString("FileContentNotStreamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ZentityFileStreamProvider does not support eTags for File resources..
        /// </summary>
        internal static string FileETagsNotSupported {
            get {
                return ResourceManager.GetString("FileETagsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileExtension.
        /// </summary>
        internal static string FileExtension {
            get {
                return ResourceManager.GetString("FileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; of the File resource that was sent in the slug header of the SetSaveStream method cannot be Guid.Empty (00000000-0000-0000-0000-000000000000)..
        /// </summary>
        internal static string FileIdIsGuidEmpty {
            get {
                return ResourceManager.GetString("FileIdIsGuidEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; of the File resource that was sent in the slug header of the SetSaveStream cannot be parsed. The &apos;Id&apos; value must be a valid Guid..
        /// </summary>
        internal static string FileIdIsInvalid {
            get {
                return ResourceManager.GetString("FileIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; of the File resource must be sent as the slug header of the SetSaveStream method. The &apos;Id&apos; value must be a valid Guid..
        /// </summary>
        internal static string FileIdNotSent {
            get {
                return ResourceManager.GetString("FileIdNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested File resource was not found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found in the repository. Content can be downloaded only from an existing File resource..
        /// </summary>
        internal static string FileNotFoundForDownload {
            get {
                return ResourceManager.GetString("FileNotFoundForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found in the repository. Content can be uploaded only to an existing File resource..
        /// </summary>
        internal static string FileNotFoundForUpload {
            get {
                return ResourceManager.GetString("FileNotFoundForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slug.
        /// </summary>
        internal static string HttpHeaderSlug {
            get {
                return ResourceManager.GetString("HttpHeaderSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration name cannot be a null reference or an empty string..
        /// </summary>
        internal static string InvalidConfigNameNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidConfigNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Id&apos; property value of the entity cannot be Guid.Empty..
        /// </summary>
        internal static string InvalidIdForEntity {
            get {
                return ResourceManager.GetString("InvalidIdForEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified input file does not exist..
        /// </summary>
        internal static string InvalidInputPathNonExisting {
            get {
                return ResourceManager.GetString("InvalidInputPathNonExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input path cannot be a null reference or an empty string..
        /// </summary>
        internal static string InvalidInputPathNullOrEmtpy {
            get {
                return ResourceManager.GetString("InvalidInputPathNullOrEmtpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input stream does not support reading. The input stream must support reading for copying to work..
        /// </summary>
        internal static string InvalidInputStream {
            get {
                return ResourceManager.GetString("InvalidInputStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path cannot be a null reference or an empty string..
        /// </summary>
        internal static string InvalidOutputPathNullOrEmpty {
            get {
                return ResourceManager.GetString("InvalidOutputPathNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output stream does not support writing. For copying to work, the output stream must support writing..
        /// </summary>
        internal static string InvalidOutputStream {
            get {
                return ResourceManager.GetString("InvalidOutputStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MimeType.
        /// </summary>
        internal static string MimeType {
            get {
                return ResourceManager.GetString("MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PathName.
        /// </summary>
        internal static string PathName {
            get {
                return ResourceManager.GetString("PathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductVersion.
        /// </summary>
        internal static string ProductVersion {
            get {
                return ResourceManager.GetString("ProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyName.
        /// </summary>
        internal static string PropertyName {
            get {
                return ResourceManager.GetString("PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyValue.
        /// </summary>
        internal static string PropertyValue {
            get {
                return ResourceManager.GetString("PropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceId.
        /// </summary>
        internal static string ResourceId {
            get {
                return ResourceManager.GetString("ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionContext.
        /// </summary>
        internal static string TransactionContext {
            get {
                return ResourceManager.GetString("TransactionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        internal static string Uri {
            get {
                return ResourceManager.GetString("Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of property [{0}] cannot be greater than {1}..
        /// </summary>
        internal static string ValidationExceptionInvalidLength {
            get {
                return ResourceManager.GetString("ValidationExceptionInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar property name cannot be null or empty..
        /// </summary>
        internal static string ValidationExceptionScalarPropertyNameNullOrEmpty {
            get {
                return ResourceManager.GetString("ValidationExceptionScalarPropertyNameNullOrEmpty", resourceCulture);
            }
        }
    }
}
