//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.CollectionCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.CollectionCreator.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding or Updating the Resource.
        /// </summary>
        internal static string AddUpdateResourceMessage {
            get {
                return ResourceManager.GetString("AddUpdateResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        internal static string AssociationException {
            get {
                return ResourceManager.GetString("AssociationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Association found in the Data Model.
        /// </summary>
        internal static string AssociationFaultReason {
            get {
                return ResourceManager.GetString("AssociationFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the Base Resource Type for the Model Namespace provided..
        /// </summary>
        internal static string BaseResourceTypeFaultReason {
            get {
                return ResourceManager.GetString("BaseResourceTypeFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Configuratin Xml from the Resource Type&apos;s Properties..
        /// </summary>
        internal static string ConfigXmlCreation {
            get {
                return ResourceManager.GetString("ConfigXmlCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Configuration Xml from Database..
        /// </summary>
        internal static string ConfigXmlDB {
            get {
                return ResourceManager.GetString("ConfigXmlDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get the Data Model for the given context..
        /// </summary>
        internal static string ContextFaultReason {
            get {
                return ResourceManager.GetString("ContextFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of Cxml&apos;s for Navigation properties finished..
        /// </summary>
        internal static string CxmlForNavPropertiesFinishedMessage {
            get {
                return ResourceManager.GetString("CxmlForNavPropertiesFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of Cxml&apos;s for Navigation properties started..
        /// </summary>
        internal static string CxmlForNavPropertiesStartedMessage {
            get {
                return ResourceManager.GetString("CxmlForNavPropertiesStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataModel: {0}.
        /// </summary>
        internal static string DataModelFormat {
            get {
                return ResourceManager.GetString("DataModelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the Resource.
        /// </summary>
        internal static string DeleteResourceMessage {
            get {
                return ResourceManager.GetString("DeleteResourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination folder for the assemblies is null/empty or is not found. Check whether the folder exists and try again..
        /// </summary>
        internal static string DestinationAssemblyFolderPathFaultReason {
            get {
                return ResourceManager.GetString("DestinationAssemblyFolderPathFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dispatcher was null..
        /// </summary>
        internal static string DispatcherNull {
            get {
                return ResourceManager.GetString("DispatcherNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Model is already part of this Module..
        /// </summary>
        internal static string DuplicateDataModelFaultReason {
            get {
                return ResourceManager.GetString("DuplicateDataModelFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add Scalar Property since the Property is already part of the Resource Type..
        /// </summary>
        internal static string DuplicateScalarPropertyFaultReason {
            get {
                return ResourceManager.GetString("DuplicateScalarPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError Message :- \n{0}\n.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pivot Config section was not specified or required elements were not defined..
        /// </summary>
        internal static string ErrorWarningTitle {
            get {
                return ResourceManager.GetString("ErrorWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exeption was thrown, see inner exception for details..
        /// </summary>
        internal static string ExceptionFaultReason {
            get {
                return ResourceManager.GetString("ExceptionFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught exception in create image thread: {0}.
        /// </summary>
        internal static string ExceptionInCreateImageThread {
            get {
                return ResourceManager.GetString("ExceptionInCreateImageThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught exception in rendering thread: {0}.
        /// </summary>
        internal static string ExceptionInRenderingThread {
            get {
                return ResourceManager.GetString("ExceptionInRenderingThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught exception in web browser invoke method: {0}.
        /// </summary>
        internal static string ExceptionInvokingBrowser {
            get {
                return ResourceManager.GetString("ExceptionInvokingBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError   : Exception occurred. Check below for trace information.
        /// </summary>
        internal static string ExceptionOccured {
            get {
                return ResourceManager.GetString("ExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an image for &apos;{0}&apos; in within {1} seconds.
        /// </summary>
        internal static string FailedCreatingImageInTime {
            get {
                return ResourceManager.GetString("FailedCreatingImageInTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Load Assemblies into ZentityContext..
        /// </summary>
        internal static string FailLoadAssemblyTitle {
            get {
                return ResourceManager.GetString("FailLoadAssemblyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Function.
        /// </summary>
        internal static string FinishedFunctionMessage {
            get {
                return ResourceManager.GetString("FinishedFunctionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate assembly.
        /// </summary>
        internal static string GenerateAssemblyFailedFaultReason {
            get {
                return ResourceManager.GetString("GenerateAssemblyFailedFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be at least 1: {0}.
        /// </summary>
        internal static string HeightMustbeAtleastOne {
            get {
                return ResourceManager.GetString("HeightMustbeAtleastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be less than {0} : {1}.
        /// </summary>
        internal static string HeightMustBeLessThan {
            get {
                return ResourceManager.GetString("HeightMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image rendering failed: {0}.
        /// </summary>
        internal static string ImageRenderingFailure {
            get {
                return ResourceManager.GetString("ImageRenderingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Data Model Namespace is invalid in the given context..
        /// </summary>
        internal static string InvalidDataModelFaultReason {
            get {
                return ResourceManager.GetString("InvalidDataModelFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The outputAssemblyName provided contains some illegal characters..
        /// </summary>
        internal static string InvalidFileNameFaultReason {
            get {
                return ResourceManager.GetString("InvalidFileNameFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Metadata Namespaces provided..
        /// </summary>
        internal static string InvalidMetadataNamespaceFaultReason {
            get {
                return ResourceManager.GetString("InvalidMetadataNamespaceFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model Namespaces provided..
        /// </summary>
        internal static string InvalidModelNamespaceFaultReason {
            get {
                return ResourceManager.GetString("InvalidModelNamespaceFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError : Invalid operation or operation not defined.\n.
        /// </summary>
        internal static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError : Invalid switch &apos;{0}&apos;\n.
        /// </summary>
        internal static string InvalidSwitch {
            get {
                return ResourceManager.GetString("InvalidSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError : Invalid switch and value pattern &apos;{0}&apos;.\n.
        /// </summary>
        internal static string InvalidSwitchAndValuePattern {
            get {
                return ResourceManager.GetString("InvalidSwitchAndValuePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nError : Invalid switch &apos;{0}&apos;. Please check help for valid switches.\n.
        /// </summary>
        internal static string InvalidSwitchWithHelp {
            get {
                return ResourceManager.GetString("InvalidSwitchWithHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebCapture type information is invalid..
        /// </summary>
        internal static string InvalidWebCaptureType {
            get {
                return ResourceManager.GetString("InvalidWebCaptureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nMessage : {0}\n.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modelConfiguration.
        /// </summary>
        internal static string ModelConfigurationParameter {
            get {
                return ResourceManager.GetString("ModelConfigurationParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modelNamespace.
        /// </summary>
        internal static string ModelNamespaceParameter {
            get {
                return ResourceManager.GetString("ModelNamespaceParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NavigationPropertyCollection.
        /// </summary>
        internal static string NavigationPropertyCollectionException {
            get {
                return ResourceManager.GetString("NavigationPropertyCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Property.
        /// </summary>
        internal static string NavigationPropertyException {
            get {
                return ResourceManager.GetString("NavigationPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add Navigation Property since the Property is already part of the Resource Type..
        /// </summary>
        internal static string NavigationPropertyFaultReason {
            get {
                return ResourceManager.GetString("NavigationPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource to delete..
        /// </summary>
        internal static string NoResourceToDeleteMessage {
            get {
                return ResourceManager.GetString("NoResourceToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Navigation Property for the Resource Type..
        /// </summary>
        internal static string NotFoundNavigationPropertyFaultReason {
            get {
                return ResourceManager.GetString("NotFoundNavigationPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Scalar Property for the Resource Type..
        /// </summary>
        internal static string NotFoundScalarPropertyFaultReason {
            get {
                return ResourceManager.GetString("NotFoundScalarPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection or its items are null or empty..
        /// </summary>
        internal static string NullCollectionChildMessage {
            get {
                return ResourceManager.GetString("NullCollectionChildMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cxml file list was null..
        /// </summary>
        internal static string NullCxmlFileListMessage {
            get {
                return ResourceManager.GetString("NullCxmlFileListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Model with the namespace provided exits in the current context..
        /// </summary>
        internal static string NullDataModelFaultReason {
            get {
                return ResourceManager.GetString("NullDataModelFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination output folder for the cxml generation is not specified..
        /// </summary>
        internal static string NullDestinationOuputMessage {
            get {
                return ResourceManager.GetString("NullDestinationOuputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more arguments for this method are null or empty..
        /// </summary>
        internal static string NullEmptyMessage {
            get {
                return ResourceManager.GetString("NullEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Method returned string.Empty or null..
        /// </summary>
        internal static string NullEmptyStringMessage {
            get {
                return ResourceManager.GetString("NullEmptyStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null/Empty Arguments.
        /// </summary>
        internal static string NullEmptyTitle {
            get {
                return ResourceManager.GetString("NullEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cxmlFacetCategories is null or empty..
        /// </summary>
        internal static string NullFacetCategoriesMessage {
            get {
                return ResourceManager.GetString("NullFacetCategoriesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemExtension is null or empty..
        /// </summary>
        internal static string NullItemExtensinTitle {
            get {
                return ResourceManager.GetString("NullItemExtensinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modelConfiguration was null or empty..
        /// </summary>
        internal static string NullModelConfigurationMessage {
            get {
                return ResourceManager.GetString("NullModelConfigurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modelNamespace is either null or not valid in the current context..
        /// </summary>
        internal static string NullModelNamespaceMessage {
            get {
                return ResourceManager.GetString("NullModelNamespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The navigation property collection is null or empty..
        /// </summary>
        internal static string NullNavigationPropertyCollectionFaultReason {
            get {
                return ResourceManager.GetString("NullNavigationPropertyCollectionFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception during creation of Navigation Property..
        /// </summary>
        internal static string NullNavigationPropertyFaultReason {
            get {
                return ResourceManager.GetString("NullNavigationPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pivot Config section was not specifed in the Config file..
        /// </summary>
        internal static string NullPivotConfigSectionMessage {
            get {
                return ResourceManager.GetString("NullPivotConfigSectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource change message list is null or does not have any messages on which processing is to be performed..
        /// </summary>
        internal static string NullResourceChangeMessage {
            get {
                return ResourceManager.GetString("NullResourceChangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type does not contain any resources in the DataBase..
        /// </summary>
        internal static string NullResourcesInDBMessage {
            get {
                return ResourceManager.GetString("NullResourcesInDBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mentioned resourceType is not present in the Data Model..
        /// </summary>
        internal static string NullResourceTypeFaultReason {
            get {
                return ResourceManager.GetString("NullResourceTypeFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Database does not contain the Resource Type. Either the DataModelNamespace or ResourceType is invalid..
        /// </summary>
        internal static string NullResourceTypeInDBMessage {
            get {
                return ResourceManager.GetString("NullResourceTypeInDBMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type setting is null. This is because the DataModelNamespace provided is not present in the Data Model or the ResourceType name provided does not exist in the Data Model..
        /// </summary>
        internal static string NullResourceTypeSettingMessage {
            get {
                return ResourceManager.GetString("NullResourceTypeSettingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Resource Types are present in the Data Model Namespace..
        /// </summary>
        internal static string NullResourceTypesFaultReason {
            get {
                return ResourceManager.GetString("NullResourceTypesFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scalar property collection is null or empty..
        /// </summary>
        internal static string NullScalarPropertyCollectionFaultReason {
            get {
                return ResourceManager.GetString("NullScalarPropertyCollectionFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scalar Properties for the Resource Type..
        /// </summary>
        internal static string NullScalarPropertyFaultReason {
            get {
                return ResourceManager.GetString("NullScalarPropertyFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Split Cxml Item List is null or empty..
        /// </summary>
        internal static string NullSplitItemListMessage {
            get {
                return ResourceManager.GetString("NullSplitItemListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebCaptureUrl is null or empty..
        /// </summary>
        internal static string NullWebCaptureUrlMessage {
            get {
                return ResourceManager.GetString("NullWebCaptureUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceType: {0}.
        /// </summary>
        internal static string ResourceTypeFormat {
            get {
                return ResourceManager.GetString("ResourceTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resourceTypeName.
        /// </summary>
        internal static string ResourceTypeNameParameter {
            get {
                return ResourceManager.GetString("ResourceTypeNameParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScalarPropertyCollection.
        /// </summary>
        internal static string ScalarPropertyCollectionException {
            get {
                return ResourceManager.GetString("ScalarPropertyCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar Property.
        /// </summary>
        internal static string ScalarPropertyException {
            get {
                return ResourceManager.GetString("ScalarPropertyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update complete. Splitting and copying the collection..
        /// </summary>
        internal static string SplitCopyCalledAfterUpdateMessage {
            get {
                return ResourceManager.GetString("SplitCopyCalledAfterUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started Function.
        /// </summary>
        internal static string StartedFunctionMessage {
            get {
                return ResourceManager.GetString("StartedFunctionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubjectResourceType: {0}, ObjectResourceType: {1}.
        /// </summary>
        internal static string SubjectObjectResourceTypes {
            get {
                return ResourceManager.GetString("SubjectObjectResourceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This thread is already creating an image..
        /// </summary>
        internal static string ThreadAlreadyCreatingImage {
            get {
                return ResourceManager.GetString("ThreadAlreadyCreatingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying existing collection of resource type &quot;{0}&quot; to working folder..
        /// </summary>
        internal static string UpdateCollectionCopyToTempMessage {
            get {
                return ResourceManager.GetString("UpdateCollectionCopyToTempMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pivot collection for the resource type &quot;{0}&quot; is not created. Complete collection generation will be initated..
        /// </summary>
        internal static string UpdateCollectionCreateCollectionMessage {
            get {
                return ResourceManager.GetString("UpdateCollectionCreateCollectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be at least 1: {0}.
        /// </summary>
        internal static string WidthMustbeAtleastOne {
            get {
                return ResourceManager.GetString("WidthMustbeAtleastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be less than {0} : {1}.
        /// </summary>
        internal static string WidthMustBeLessThan {
            get {
                return ResourceManager.GetString("WidthMustBeLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Parse the one of the xml files..
        /// </summary>
        internal static string XmlParseFaultReason {
            get {
                return ResourceManager.GetString("XmlParseFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zentity Context.
        /// </summary>
        internal static string ZentityContext {
            get {
                return ResourceManager.GetString("ZentityContext", resourceCulture);
            }
        }
    }
}
