//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Web.UI.ToolKit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Web.UI.ToolKit.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-E.
        /// </summary>
        internal static string A_EText {
            get {
                return ResourceManager.GetString("A_EText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Child Node.
        /// </summary>
        internal static string AddCategoryNode {
            get {
                return ResourceManager.GetString("AddCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode &apos;{0}&apos; added successfully..
        /// </summary>
        internal static string AddedCategory {
            get {
                return ResourceManager.GetString("AddedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to view full size image.
        /// </summary>
        internal static string AlternateThumbImageText {
            get {
                return ResourceManager.GetString("AlternateThumbImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Resource(s).
        /// </summary>
        internal static string AssociationAvailableResources {
            get {
                return ResourceManager.GetString("AssociationAvailableResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available {0}(s).
        /// </summary>
        internal static string AssociationAvailableTags {
            get {
                return ResourceManager.GetString("AssociationAvailableTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string AssociationButtonTextMoveDown {
            get {
                return ResourceManager.GetString("AssociationButtonTextMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string AssociationButtonTextMoveLeft {
            get {
                return ResourceManager.GetString("AssociationButtonTextMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string AssociationButtonTextMoveRight {
            get {
                return ResourceManager.GetString("AssociationButtonTextMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string AssociationButtonTextMoveUp {
            get {
                return ResourceManager.GetString("AssociationButtonTextMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association.
        /// </summary>
        internal static string AssociationDefaultHeader {
            get {
                return ResourceManager.GetString("AssociationDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string AssociationFilterButton {
            get {
                return ResourceManager.GetString("AssociationFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        internal static string AssociationObjectTypeLabel {
            get {
                return ResourceManager.GetString("AssociationObjectTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicate.
        /// </summary>
        internal static string AssociationPredicateLabel {
            get {
                return ResourceManager.GetString("AssociationPredicateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Resource(s).
        /// </summary>
        internal static string AssociationSelectedResources {
            get {
                return ResourceManager.GetString("AssociationSelectedResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected {0}(s).
        /// </summary>
        internal static string AssociationSelectedTags {
            get {
                return ResourceManager.GetString("AssociationSelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string AssociationSubjectLabel {
            get {
                return ResourceManager.GetString("AssociationSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atom Feed.
        /// </summary>
        internal static string AtomTooltip {
            get {
                return ResourceManager.GetString("AtomTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string AuthorsText {
            get {
                return ResourceManager.GetString("AuthorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as BibTeX.
        /// </summary>
        internal static string BibTexExportLabel {
            get {
                return ResourceManager.GetString("BibTexExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import as BibTeX.
        /// </summary>
        internal static string BibTexImportLabel {
            get {
                return ResourceManager.GetString("BibTexImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Binary Data&gt;.
        /// </summary>
        internal static string BinaryDataText {
            get {
                return ResourceManager.GetString("BinaryDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDeleteText {
            get {
                return ResourceManager.GetString("ButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Association.
        /// </summary>
        internal static string ButtonEditAssociationText {
            get {
                return ResourceManager.GetString("ButtonEditAssociationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ButtonEditText {
            get {
                return ResourceManager.GetString("ButtonEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ButtonNextText {
            get {
                return ResourceManager.GetString("ButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string ButtonPermisstionText {
            get {
                return ResourceManager.GetString("ButtonPermisstionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string ButtonPrevText {
            get {
                return ResourceManager.GetString("ButtonPrevText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        internal static string ButtonSubmitText {
            get {
                return ResourceManager.GetString("ButtonSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalenderAltText {
            get {
                return ResourceManager.GetString("CalenderAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Association Changes.
        /// </summary>
        internal static string CategoryAssociationChangesText {
            get {
                return ResourceManager.GetString("CategoryAssociationChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string CategoryAssociationSubjectLabel {
            get {
                return ResourceManager.GetString("CategoryAssociationSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode Properties.
        /// </summary>
        internal static string CategoryNodeProperty {
            get {
                return ResourceManager.GetString("CategoryNodeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Association related change sets will  appear in this section..
        /// </summary>
        internal static string ChangeHistoryDesignerCateAssociation {
            get {
                return ResourceManager.GetString("ChangeHistoryDesignerCateAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship related change sets will appear in this section..
        /// </summary>
        internal static string ChangeHistoryDesignerRelationship {
            get {
                return ResourceManager.GetString("ChangeHistoryDesignerRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Tagging related change sets will  appear in this section..
        /// </summary>
        internal static string ChangeHistoryDesignerResTagging {
            get {
                return ResourceManager.GetString("ChangeHistoryDesignerResTagging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar property related change sets will appear in this section.
        /// </summary>
        internal static string ChangeHistoryDesignerScalarProperty {
            get {
                return ResourceManager.GetString("ChangeHistoryDesignerScalarProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity might have been deleted.
        /// </summary>
        internal static string ChangeHistoryEntityNotFound {
            get {
                return ResourceManager.GetString("ChangeHistoryEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change History Logging features is not enabled. Please enable it to record the change history details..
        /// </summary>
        internal static string ChangeHistoryFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ChangeHistoryFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been updated by another user. It should be refreshed..
        /// </summary>
        internal static string ConcurrentAccessExceptionMessage {
            get {
                return ResourceManager.GetString("ConcurrentAccessExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContextStyle.
        /// </summary>
        internal static string ContextMenuStyle {
            get {
                return ResourceManager.GetString("ContextMenuStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control is not render.
        /// </summary>
        internal static string ControlNotRender {
            get {
                return ResourceManager.GetString("ControlNotRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new root node....
        /// </summary>
        internal static string CreateNewRootCategoryNode {
            get {
                return ResourceManager.GetString("CreateNewRootCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to center.
        /// </summary>
        internal static string CssButtonTextAlignCenter {
            get {
                return ResourceManager.GetString("CssButtonTextAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white-space:nowrap.
        /// </summary>
        internal static string CssCheckBoxListStyle {
            get {
                return ResourceManager.GetString("CssCheckBoxListStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string CssControlWidth100Percent {
            get {
                return ResourceManager.GetString("CssControlWidth100Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        internal static string CssDivAssociationOverflow {
            get {
                return ResourceManager.GetString("CssDivAssociationOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1px #888888 solid.
        /// </summary>
        internal static string CssDivBorder {
            get {
                return ResourceManager.GetString("CssDivBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100px.
        /// </summary>
        internal static string CssListAuthorWidth {
            get {
                return ResourceManager.GetString("CssListAuthorWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string CssPanelDisplayNone {
            get {
                return ResourceManager.GetString("CssPanelDisplayNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2px.
        /// </summary>
        internal static string CssPanelPadding {
            get {
                return ResourceManager.GetString("CssPanelPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65%.
        /// </summary>
        internal static string CssScrollableContainerWidth {
            get {
                return ResourceManager.GetString("CssScrollableContainerWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10px.
        /// </summary>
        internal static string CssSubjectLinkPanelMargin {
            get {
                return ResourceManager.GetString("CssSubjectLinkPanelMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200px.
        /// </summary>
        internal static string CssTextFilterWidth {
            get {
                return ResourceManager.GetString("CssTextFilterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bottom.
        /// </summary>
        internal static string CssVerticalAlignBottom {
            get {
                return ResourceManager.GetString("CssVerticalAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutCategoryNode {
            get {
                return ResourceManager.GetString("CutCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode cut/paste is cyclic.
        /// </summary>
        internal static string CutPasteError {
            get {
                return ResourceManager.GetString("CutPasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode cut/paste successfully.
        /// </summary>
        internal static string CutPateCategory {
            get {
                return ResourceManager.GetString("CutPateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        internal static string DateAddedText {
            get {
                return ResourceManager.GetString("DateAddedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string DateModifiedText {
            get {
                return ResourceManager.GetString("DateModifiedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryHierarchy.
        /// </summary>
        internal static string DefaultCategoryHierarchyCaption {
            get {
                return ResourceManager.GetString("DefaultCategoryHierarchyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultButton.
        /// </summary>
        internal static string DefaultContextButtonStyle {
            get {
                return ResourceManager.GetString("DefaultContextButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Cloud.
        /// </summary>
        internal static string DefaultRelatedResourceCloudText {
            get {
                return ResourceManager.GetString("DefaultRelatedResourceCloudText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Resources.
        /// </summary>
        internal static string DefaultRelatedResourcesText {
            get {
                return ResourceManager.GetString("DefaultRelatedResourcesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Info.
        /// </summary>
        internal static string DefaultResourceInfoText {
            get {
                return ResourceManager.GetString("DefaultResourceInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this record?.
        /// </summary>
        internal static string DeleteButtonMessage {
            get {
                return ResourceManager.GetString("DeleteButtonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        internal static string DeleteCategoryNode {
            get {
                return ResourceManager.GetString("DeleteCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CategoryNode and its respective associations will be deleted. \r\nAre you sure you wish to delete selected CategoryNode?.
        /// </summary>
        internal static string DeletecategoryNodeConfirmation {
            get {
                return ResourceManager.GetString("DeletecategoryNodeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete existing file.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionText {
            get {
                return ResourceManager.GetString("DescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node1.
        /// </summary>
        internal static string DesignModecategoryNodeText {
            get {
                return ResourceManager.GetString("DesignModecategoryNodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abc.
        /// </summary>
        internal static string DesignTimeDummyDataString {
            get {
                return ResourceManager.GetString("DesignTimeDummyDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Association.
        /// </summary>
        internal static string EditAssociationButtonText {
            get {
                return ResourceManager.GetString("EditAssociationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Node.
        /// </summary>
        internal static string EditCategoryNode {
            get {
                return ResourceManager.GetString("EditCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Resource Info.
        /// </summary>
        internal static string EditResourceInfoLinkText {
            get {
                return ResourceManager.GetString("EditResourceInfoLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity could not be found..
        /// </summary>
        internal static string EntityNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("EntityNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource should be of type List of Contact/Organization..
        /// </summary>
        internal static string ExceptionDatasourceContactGridView {
            get {
                return ResourceManager.GetString("ExceptionDatasourceContactGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource should be of type List of Person..
        /// </summary>
        internal static string ExceptionDatasourcePersonGridView {
            get {
                return ResourceManager.GetString("ExceptionDatasourcePersonGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource should be of type List of Resource..
        /// </summary>
        internal static string ExceptionDataSourceResourceGridView {
            get {
                return ResourceManager.GetString("ExceptionDataSourceResourceGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSource should be of type List of Tag..
        /// </summary>
        internal static string ExceptionDataSourceTagGridView {
            get {
                return ResourceManager.GetString("ExceptionDataSourceTagGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort expression is not valid for selected column..
        /// </summary>
        internal static string ExceptionSortExpressionZentityGridView {
            get {
                return ResourceManager.GetString("ExceptionSortExpressionZentityGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-J.
        /// </summary>
        internal static string F_JText {
            get {
                return ResourceManager.GetString("F_JText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FilesText {
            get {
                return ResourceManager.GetString("FilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string FilterAddButtonText {
            get {
                return ResourceManager.GetString("FilterAddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string FilterConditionColumnHeader {
            get {
                return ResourceManager.GetString("FilterConditionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string FilterOperatorColumnHeader {
            get {
                return ResourceManager.GetString("FilterOperatorColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string FilterPropertyColumnHeader {
            get {
                return ResourceManager.GetString("FilterPropertyColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string FilterRemoveButtonText {
            get {
                return ResourceManager.GetString("FilterRemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string FilterValueColumnHeader {
            get {
                return ResourceManager.GetString("FilterValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighlightButton.
        /// </summary>
        internal static string HighLightContextButtonStyle {
            get {
                return ResourceManager.GetString("HighLightContextButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageScalarProperpty {
            get {
                return ResourceManager.GetString("ImageScalarProperpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria  {0}: Invalid date for {1}. Valid format: {2}..
        /// </summary>
        internal static string InvalidCriteria {
            get {
                return ResourceManager.GetString("InvalidCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria  {0}:   Invalid number or Number out of range for {1}..
        /// </summary>
        internal static string InvalidCriteriaNumber {
            get {
                return ResourceManager.GetString("InvalidCriteriaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date. Valid format: {0}..
        /// </summary>
        internal static string InvalidDateErrorMessage {
            get {
                return ResourceManager.GetString("InvalidDateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to should not be greater than.
        /// </summary>
        internal static string InvalidDateRangeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidDateRangeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File.
        /// </summary>
        internal static string InvalidDownloadFile {
            get {
                return ResourceManager.GetString("InvalidDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email.
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file type.
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path.
        /// </summary>
        internal static string InvalidFileUploadPath {
            get {
                return ResourceManager.GetString("InvalidFileUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number OR Number out of range.
        /// </summary>
        internal static string InvalidNumberErrorMessage {
            get {
                return ResourceManager.GetString("InvalidNumberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type is not valid.
        /// </summary>
        internal static string InvalidResourceType {
            get {
                return ResourceManager.GetString("InvalidResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K-O.
        /// </summary>
        internal static string K_OText {
            get {
                return ResourceManager.GetString("K_OText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Search.
        /// </summary>
        internal static string LabelMainTitleText {
            get {
                return ResourceManager.GetString("LabelMainTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        internal static string LabelOfText {
            get {
                return ResourceManager.GetString("LabelOfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        internal static string LabelPageSizeListText {
            get {
                return ResourceManager.GetString("LabelPageSizeListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string LabelPageText {
            get {
                return ResourceManager.GetString("LabelPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        internal static string LabelResourceTypeText {
            get {
                return ResourceManager.GetString("LabelResourceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeds max text length..
        /// </summary>
        internal static string LengthValidatorMessage {
            get {
                return ResourceManager.GetString("LengthValidatorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        internal static string LinkButtonFirstText {
            get {
                return ResourceManager.GetString("LinkButtonFirstText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string LinkButtonLastText {
            get {
                return ResourceManager.GetString("LinkButtonLastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string LinkButtonNextText {
            get {
                return ResourceManager.GetString("LinkButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string LinkButtonPreviousText {
            get {
                return ResourceManager.GetString("LinkButtonPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum font size must be greater than minimum font size and greater than zero.
        /// </summary>
        internal static string MaximumFontSizeGreaterThanMinFontSize {
            get {
                return ResourceManager.GetString("MaximumFontSizeGreaterThanMinFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum tags to be fetched must be greater zero.
        /// </summary>
        internal static string MaximumTagsFetchException {
            get {
                return ResourceManager.GetString("MaximumTagsFetchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected records and their respective associations will be deleted. \r\nAre you sure you wish to delete selected records?.
        /// </summary>
        internal static string MessageDeleteRecords {
            get {
                return ResourceManager.GetString("MessageDeleteRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityType cannot be null.
        /// </summary>
        internal static string MessageEntityTypeNull {
            get {
                return ResourceManager.GetString("MessageEntityTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid EntityType.
        /// </summary>
        internal static string MessageInvalidEntityType {
            get {
                return ResourceManager.GetString("MessageInvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string MessageNoRecordFound {
            get {
                return ResourceManager.GetString("MessageNoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one record!.
        /// </summary>
        internal static string MessageRecordNotSelected {
            get {
                return ResourceManager.GetString("MessageRecordNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on Go/Submit to get results for the modified criteria..
        /// </summary>
        internal static string MessageRefreshPage {
            get {
                return ResourceManager.GetString("MessageRefreshPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find ViewColumn in the properties of selected EntityType.
        /// </summary>
        internal static string MessageViewColumnNotFound {
            get {
                return ResourceManager.GetString("MessageViewColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewColumn cannot be null.
        /// </summary>
        internal static string MessageViewColumnNull {
            get {
                return ResourceManager.GetString("MessageViewColumnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum font size must be less than maximum font size and greater than zero.
        /// </summary>
        internal static string MinimumFontSizeLessThanMaxFontSize {
            get {
                return ResourceManager.GetString("MinimumFontSizeLessThanMaxFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sept,Oct,Nov,Dec.
        /// </summary>
        internal static string MonthsOfYear {
            get {
                return ResourceManager.GetString("MonthsOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no categories present..
        /// </summary>
        internal static string MsgCategoriesNotPresent {
            get {
                return ResourceManager.GetString("MsgCategoriesNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScholarlyWorkItem to CategoryNode association updated successfully..
        /// </summary>
        internal static string MsgCategoryNodeAssociationSuccessfull {
            get {
                return ResourceManager.GetString("MsgCategoryNodeAssociationSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode not found..
        /// </summary>
        internal static string MsgCategoryNodeNotFound {
            get {
                return ResourceManager.GetString("MsgCategoryNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic association detected for subject resource {0} to object resource {1} association..
        /// </summary>
        internal static string MsgCircularAssociationDetected {
            get {
                return ResourceManager.GetString("MsgCircularAssociationDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete operation on CategoryNode failed..
        /// </summary>
        internal static string MsgDeleteCategoryOperationFailed {
            get {
                return ResourceManager.GetString("MsgDeleteCategoryOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Node deleted successfully.
        /// </summary>
        internal static string MsgDeletedCategory {
            get {
                return ResourceManager.GetString("MsgDeletedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object resource {1} can have at most one association as an object and since  it is already associated to another resource, subject resource {0} cannot be associated with it..
        /// </summary>
        internal static string MsgObjectAlreadyAssociated {
            get {
                return ResourceManager.GetString("MsgObjectAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page index should be greater than or equal to 0..
        /// </summary>
        internal static string MsgPageIndexLessThanZero {
            get {
                return ResourceManager.GetString("MsgPageIndexLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size should be greater than or equal 0..
        /// </summary>
        internal static string MsgPageSizeLessThanZero {
            get {
                return ResourceManager.GetString("MsgPageSizeLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        internal static string MsgResourceNotFound {
            get {
                return ResourceManager.GetString("MsgResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found. Or user is not having enough permissions to view the resource..
        /// </summary>
        internal static string MsgResourceNotFoundOrNoViewPermission {
            get {
                return ResourceManager.GetString("MsgResourceNotFoundOrNoViewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject resource {0} cannot be associated with more than one object resource..
        /// </summary>
        internal static string MsgSubCannotAssociateWithMoreThanOneObj {
            get {
                return ResourceManager.GetString("MsgSubCannotAssociateWithMoreThanOneObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total pages should be greater than or equal to 0..
        /// </summary>
        internal static string MsgTotalPagesLessThanZero {
            get {
                return ResourceManager.GetString("MsgTotalPagesLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total records should be greater than or equal to 0..
        /// </summary>
        internal static string MsgTotalRecordLessThanZero {
            get {
                return ResourceManager.GetString("MsgTotalRecordLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file to download. It might have been deleted..
        /// </summary>
        internal static string NoFileDownload {
            get {
                return ResourceManager.GetString("NoFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /App_Themes/Granite/Images/NoImage.JPG.
        /// </summary>
        internal static string NoImageUrl {
            get {
                return ResourceManager.GetString("NoImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string OthersText {
            get {
                return ResourceManager.GetString("OthersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-T.
        /// </summary>
        internal static string P_TText {
            get {
                return ResourceManager.GetString("P_TText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PageSize10 {
            get {
                return ResourceManager.GetString("PageSize10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string PageSize15 {
            get {
                return ResourceManager.GetString("PageSize15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string PageSize25 {
            get {
                return ResourceManager.GetString("PageSize25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string PageSize50 {
            get {
                return ResourceManager.GetString("PageSize50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PasteCategoryNode {
            get {
                return ResourceManager.GetString("PasteCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PersonEmailDefaultHeader {
            get {
                return ResourceManager.GetString("PersonEmailDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string PersonFirstNameDefaultHeader {
            get {
                return ResourceManager.GetString("PersonFirstNameDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string PersonLastNameDefaultHeader {
            get {
                return ResourceManager.GetString("PersonLastNameDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string PersonMiddleNameDefaultHeader {
            get {
                return ResourceManager.GetString("PersonMiddleNameDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type does not exist..
        /// </summary>
        internal static string PredicateAssociationResourceTypeErrorMessage {
            get {
                return ResourceManager.GetString("PredicateAssociationResourceTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject entity does not exist. It might have been deleted..
        /// </summary>
        internal static string PredicateAssociationSubjectEntityErrorMessage {
            get {
                return ResourceManager.GetString("PredicateAssociationSubjectEntityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string RadioButtonAllText {
            get {
                return ResourceManager.GetString("RadioButtonAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string RadioButtonFilterText {
            get {
                return ResourceManager.GetString("RadioButtonFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in input..
        /// </summary>
        internal static string RegularExpressionError {
            get {
                return ResourceManager.GetString("RegularExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Downloads.
        /// </summary>
        internal static string RelatedDownloadsLabelText {
            get {
                return ResourceManager.GetString("RelatedDownloadsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string RelatedResourceEditLinkText {
            get {
                return ResourceManager.GetString("RelatedResourceEditLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Changes.
        /// </summary>
        internal static string RelationshipChangesText {
            get {
                return ResourceManager.GetString("RelationshipChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,DateAdded,DateModified,Description,Uri.
        /// </summary>
        internal static string RenderingOrder1 {
            get {
                return ResourceManager.GetString("RenderingOrder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title,Description,Uri.
        /// </summary>
        internal static string RenderingOrder2 {
            get {
                return ResourceManager.GetString("RenderingOrder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0}.
        /// </summary>
        internal static string Requiredproperty {
            get {
                return ResourceManager.GetString("Requiredproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string ResourceAuthorsDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceAuthorsDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author1.
        /// </summary>
        internal static string ResourceContactTitle1 {
            get {
                return ResourceManager.GetString("ResourceContactTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        internal static string ResourceContributorsDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceContributorsDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        internal static string ResourceDateAddedDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceDateAddedDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string ResourceDateModifiedDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceDateModifiedDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description here.
        /// </summary>
        internal static string ResourceDescription {
            get {
                return ResourceManager.GetString("ResourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some description goes here...
        /// </summary>
        internal static string ResourceDescription1 {
            get {
                return ResourceManager.GetString("ResourceDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no title&gt;.
        /// </summary>
        internal static string ResourceEmptyTitle {
            get {
                return ResourceManager.GetString("ResourceEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File1.
        /// </summary>
        internal static string ResourceFileTitle1 {
            get {
                return ResourceManager.GetString("ResourceFileTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceProperties.
        /// </summary>
        internal static string ResourcePropertiesTitle {
            get {
                return ResourceManager.GetString("ResourcePropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Tagging Changes.
        /// </summary>
        internal static string ResourceTaggingChangesText {
            get {
                return ResourceManager.GetString("ResourceTaggingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        internal static string ResourceText {
            get {
                return ResourceManager.GetString("ResourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcd.
        /// </summary>
        internal static string ResourceTitle {
            get {
                return ResourceManager.GetString("ResourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resource Title.
        /// </summary>
        internal static string ResourceTitle1 {
            get {
                return ResourceManager.GetString("ResourceTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Title.
        /// </summary>
        internal static string ResourceTitleDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceTitleDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type.
        /// </summary>
        internal static string ResourceTypeDefaultHeader {
            get {
                return ResourceManager.GetString("ResourceTypeDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource type full name is required..
        /// </summary>
        internal static string ResourceTypeFullNameRequired {
            get {
                return ResourceManager.GetString("ResourceTypeFullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RootNode.
        /// </summary>
        internal static string RootCategoryNode {
            get {
                return ResourceManager.GetString("RootCategoryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS Feed.
        /// </summary>
        internal static string RSSTooltip {
            get {
                return ResourceManager.GetString("RSSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar Property Changes.
        /// </summary>
        internal static string ScalarPropertyChangeText {
            get {
                return ResourceManager.GetString("ScalarPropertyChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string ScopeHeader {
            get {
                return ResourceManager.GetString("ScopeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SearchResultTitleText {
            get {
                return ResourceManager.GetString("SearchResultTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select/Deselect All.
        /// </summary>
        internal static string SelectDeselectLabelText {
            get {
                return ResourceManager.GetString("SelectDeselectLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set IsFeedSupported to true at the time of creation of this control instance..
        /// </summary>
        internal static string SetIsFeedSupportedMessage {
            get {
                return ResourceManager.GetString("SetIsFeedSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortBy : .
        /// </summary>
        internal static string SortByLabelText {
            get {
                return ResourceManager.GetString("SortByLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string SourceListSizeText {
            get {
                return ResourceManager.GetString("SourceListSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Tagged resources: {1}).
        /// </summary>
        internal static string TagCloudEntryToolTip {
            get {
                return ResourceManager.GetString("TagCloudEntryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string TagDeleteButtonText {
            get {
                return ResourceManager.GetString("TagDeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TagDescriptionDefaultHeader {
            get {
                return ResourceManager.GetString("TagDescriptionDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TagDescriptionHeader {
            get {
                return ResourceManager.GetString("TagDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Association.
        /// </summary>
        internal static string TagEditAssociationButtonText {
            get {
                return ResourceManager.GetString("TagEditAssociationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string TagEditButtonText {
            get {
                return ResourceManager.GetString("TagEditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag1,Tag2,Tag3,Tag4,Tag5,Tag6,Tag7,Tag8,Tag9,Tag10.
        /// </summary>
        internal static string TagNameCollection {
            get {
                return ResourceManager.GetString("TagNameCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TagNameDefaultHeader {
            get {
                return ResourceManager.GetString("TagNameDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TagNameHeader {
            get {
                return ResourceManager.GetString("TagNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        internal static string TagUriDefaultHeader {
            get {
                return ResourceManager.GetString("TagUriDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active Authors.
        /// </summary>
        internal static string TitleMostActiveAuthors {
            get {
                return ResourceManager.GetString("TitleMostActiveAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Used Tags.
        /// </summary>
        internal static string TitleMostUsedTags {
            get {
                return ResourceManager.GetString("TitleMostUsedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Resources.
        /// </summary>
        internal static string TitleRecentResources {
            get {
                return ResourceManager.GetString("TitleRecentResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        internal static string TotalRecordCount {
            get {
                return ResourceManager.GetString("TotalRecordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string TreeViewCollapseImageToolTip {
            get {
                return ResourceManager.GetString("TreeViewCollapseImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string TreeViewExpandImageToolTip {
            get {
                return ResourceManager.GetString("TreeViewExpandImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-Z.
        /// </summary>
        internal static string U_ZText {
            get {
                return ResourceManager.GetString("U_ZText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file.Try again..
        /// </summary>
        internal static string UnableDownload {
            get {
                return ResourceManager.GetString("UnableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have {0} access to the resource..
        /// </summary>
        internal static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Delete access to the selected category or its child categories..
        /// </summary>
        internal static string UnauthorizedAccessExceptionCategoryDelete {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionCategoryDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have {0} access..
        /// </summary>
        internal static string UnauthorizedAccessExceptionCreate {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have {0} access to one or more resources on the page. Please try again..
        /// </summary>
        internal static string UnauthorizedAccessExceptionMultipleResources {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMultipleResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have Update access on the parent category node..
        /// </summary>
        internal static string UnauthorizedAccessExceptionUpdateParentCategory {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionUpdateParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryNode {0} updated successfully.
        /// </summary>
        internal static string UpdatedCategory {
            get {
                return ResourceManager.GetString("UpdatedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded File.
        /// </summary>
        internal static string UploadedFileLabelText {
            get {
                return ResourceManager.GetString("UploadedFileLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the following:.
        /// </summary>
        internal static string validationSummaryHeader {
            get {
                return ResourceManager.GetString("validationSummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Change History.
        /// </summary>
        internal static string ViewChangeHistoryLinkText {
            get {
                return ResourceManager.GetString("ViewChangeHistoryLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearText {
            get {
                return ResourceManager.GetString("YearText", resourceCulture);
            }
        }
    }
}
