//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Web.UI.ToolKit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ZentityAttributeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZentityAttributeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Web.UI.ToolKit.Resources.ZentityAttributeResource", typeof(ZentityAttributeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}:PredicateAssociation runat=\&quot;server\&quot;&gt;&lt;MoveRightButton Text =\&quot;&gt;&gt;\&quot;/&gt;&lt;MoveLeftButton Text =\&quot;&lt;&lt;\&quot;/&gt;&lt;MoveUpButton Text =\&quot;Up\&quot;/&gt;&lt;MoveDownButton Text =\&quot;Down\&quot;/&gt;&lt;/{0}:PredicateAssociation&gt;.
        /// </summary>
        internal static string AttributePredicateToolBoxData {
            get {
                return ResourceManager.GetString("AttributePredicateToolBoxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}:ScholarlyWorkItemTagging runat=\&quot;server\&quot;&gt;&lt;MoveRightButton Text =\&quot;&gt;&gt;\&quot;/&gt;&lt;MoveLeftButton Text =\&quot;&lt;&lt;\&quot;/&gt;&lt;/{0}:ScholarlyWorkItemTagging&gt;.
        /// </summary>
        internal static string AttributeScholarlyWorkToolBoxData {
            get {
                return ResourceManager.GetString("AttributeScholarlyWorkToolBoxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CategoryAppearance {
            get {
                return ResourceManager.GetString("CategoryAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string CategoryBehavior {
            get {
                return ResourceManager.GetString("CategoryBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CategoryLayout {
            get {
                return ResourceManager.GetString("CategoryLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string CategoryMisc {
            get {
                return ResourceManager.GetString("CategoryMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging.
        /// </summary>
        internal static string CategoryPaging {
            get {
                return ResourceManager.GetString("CategoryPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string CategoryStyles {
            get {
                return ResourceManager.GetString("CategoryStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets FilterBy property..
        /// </summary>
        internal static string DescriptionAssociationFilterBy {
            get {
                return ResourceManager.GetString("DescriptionAssociationFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets filter value for the selected FilterBy property..
        /// </summary>
        internal static string DescriptionAssociationFilterValue {
            get {
                return ResourceManager.GetString("DescriptionAssociationFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the height for check box lists..
        /// </summary>
        internal static string DescriptionAssociationListHeight {
            get {
                return ResourceManager.GetString("DescriptionAssociationListHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the maximum items to be displayed in source list box..
        /// </summary>
        internal static string DescriptionAssociationListSizes {
            get {
                return ResourceManager.GetString("DescriptionAssociationListSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the width for check box lists..
        /// </summary>
        internal static string DescriptionAssociationListWidth {
            get {
                return ResourceManager.GetString("DescriptionAssociationListWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets properties of the button which move the selected items in the destination list in downward direction..
        /// </summary>
        internal static string DescriptionAssociationMoveDownButton {
            get {
                return ResourceManager.GetString("DescriptionAssociationMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets properties of the button which move the selected items from destination list to source list..
        /// </summary>
        internal static string DescriptionAssociationMoveLeftButton {
            get {
                return ResourceManager.GetString("DescriptionAssociationMoveLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets properties of the button which move the selected items from source list to destination list..
        /// </summary>
        internal static string DescriptionAssociationMoveRightButton {
            get {
                return ResourceManager.GetString("DescriptionAssociationMoveRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets properties of the button which move the selected items  in the destination list in upward direction..
        /// </summary>
        internal static string DescriptionAssociationMoveUpButton {
            get {
                return ResourceManager.GetString("DescriptionAssociationMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for category association change sets..
        /// </summary>
        internal static string DescriptionCategoryAssociationChangeSetStyle {
            get {
                return ResourceManager.GetString("DescriptionCategoryAssociationChangeSetStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the connection string..
        /// </summary>
        internal static string DescriptionConnectionString {
            get {
                return ResourceManager.GetString("DescriptionConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ViewClicked event which is raised when user clicks on the link provided on Email column..
        /// </summary>
        internal static string DescriptionContactGridViewViewClicked {
            get {
                return ResourceManager.GetString("DescriptionContactGridViewViewClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or set default context button style.
        /// </summary>
        internal static string DescriptionContextDefaultStyle {
            get {
                return ResourceManager.GetString("DescriptionContextDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or set highlight context button style.
        /// </summary>
        internal static string DescriptionContextHighLightStyle {
            get {
                return ResourceManager.GetString("DescriptionContextHighLightStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get or set context menu style.
        /// </summary>
        internal static string DescriptionContextMenuStyle {
            get {
                return ResourceManager.GetString("DescriptionContextMenuStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets id of entity..
        /// </summary>
        internal static string DescriptionEntityId {
            get {
                return ResourceManager.GetString("DescriptionEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Buttons..
        /// </summary>
        internal static string DescriptionEntitySearchButtonStyle {
            get {
                return ResourceManager.GetString("DescriptionEntitySearchButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets Entity type..
        /// </summary>
        internal static string DescriptionEntitySearchEntityType {
            get {
                return ResourceManager.GetString("DescriptionEntitySearchEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Labels..
        /// </summary>
        internal static string DescriptionEntitySearchLabelStyle {
            get {
                return ResourceManager.GetString("DescriptionEntitySearchLabelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for FilterCriteria alternate row..
        /// </summary>
        internal static string DescriptionFilterCriteriaAlternateRowStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaAlternateRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Buttons..
        /// </summary>
        internal static string DescriptionFilterCriteriaButtonStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for input controls..
        /// </summary>
        internal static string DescriptionFilterCriteriaControlStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaControlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Resource Entity type.
        /// </summary>
        internal static string DescriptionFilterCriteriaEnityType {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaEnityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for FilterCriteria footer row..
        /// </summary>
        internal static string DescriptionFilterCriteriaFooterRowStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaFooterRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for FilterCriteria header row..
        /// </summary>
        internal static string DescriptionFilterCriteriaHeaderStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaHeaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Labels..
        /// </summary>
        internal static string DescriptionFilterCriteriaLabelStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaLabelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for FilterCriteria row..
        /// </summary>
        internal static string DescriptionFilterCriteriaRowStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for FilterCriteria selected row..
        /// </summary>
        internal static string DescriptionFilterCriteriaSelectedRowStyle {
            get {
                return ResourceManager.GetString("DescriptionFilterCriteriaSelectedRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate whether the Grid view should be automatically populated with the available record set..
        /// </summary>
        internal static string DescriptionGridViewAutoBindMode {
            get {
                return ResourceManager.GetString("DescriptionGridViewAutoBindMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets DeleteClicked event which is raised when user clicks on the Delete link button..
        /// </summary>
        internal static string DescriptionGridViewDeleteClicked {
            get {
                return ResourceManager.GetString("DescriptionGridViewDeleteClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets EditAssociationClicked event which is raised when user clicks on the Edit Association link button..
        /// </summary>
        internal static string DescriptionGridViewEditAssociationClicked {
            get {
                return ResourceManager.GetString("DescriptionGridViewEditAssociationClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets EditClicked event raised is fired when user clicks on the Edit link button..
        /// </summary>
        internal static string DescriptionGridViewEditClicked {
            get {
                return ResourceManager.GetString("DescriptionGridViewEditClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ViewClicked event which is raised when user clicks on the link provided on column..
        /// </summary>
        internal static string DescriptionGridViewViewClicked {
            get {
                return ResourceManager.GetString("DescriptionGridViewViewClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets count of maximum change sets to be displayed for each entity..
        /// </summary>
        internal static string DescriptionMaximumChangeSetToFetch {
            get {
                return ResourceManager.GetString("DescriptionMaximumChangeSetToFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the email column header..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsEmailHeader {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the first name column header..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsFirstNameHeader {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsFirstNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the last name column header..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsLastNameHeader {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsLastNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the middle name column header..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsMiddleNameHeader {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsMiddleNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the title column header..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsTitleHeader {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsTitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the url to be provided in title column..
        /// </summary>
        internal static string DescriptionMostActiveAuthorsTitleUrl {
            get {
                return ResourceManager.GetString("DescriptionMostActiveAuthorsTitleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the description column header..
        /// </summary>
        internal static string DescriptionMostUsedTagsDescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionMostUsedTagsDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the name column header..
        /// </summary>
        internal static string DescriptionMostUsedTagsNameHeader {
            get {
                return ResourceManager.GetString("DescriptionMostUsedTagsNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the url to be provided in Name column..
        /// </summary>
        internal static string DescriptionMostUsedTagsNameUrl {
            get {
                return ResourceManager.GetString("DescriptionMostUsedTagsNameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Uri column header..
        /// </summary>
        internal static string DescriptionMostUsedTagsUriHeader {
            get {
                return ResourceManager.GetString("DescriptionMostUsedTagsUriHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets navigation path for category..
        /// </summary>
        internal static string DescriptionNavigateUrlForCategory {
            get {
                return ResourceManager.GetString("DescriptionNavigateUrlForCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets navigation path for resource..
        /// </summary>
        internal static string DescriptionNavigateUrlForResource {
            get {
                return ResourceManager.GetString("DescriptionNavigateUrlForResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets navigation path for tag..
        /// </summary>
        internal static string DescriptionNavigateUrlForTag {
            get {
                return ResourceManager.GetString("DescriptionNavigateUrlForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ViewClicked event which is raised when user clicks on the link provided on First Name column..
        /// </summary>
        internal static string DescriptionPersonGridViewViewClicked {
            get {
                return ResourceManager.GetString("DescriptionPersonGridViewViewClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets type of resource.
        /// </summary>
        internal static string DescriptionPredicateAssociationResourceType {
            get {
                return ResourceManager.GetString("DescriptionPredicateAssociationResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets type of subject entity.
        /// </summary>
        internal static string DescriptionPredicateAssociationSubjectType {
            get {
                return ResourceManager.GetString("DescriptionPredicateAssociationSubjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets validation group on which child validator will fire..
        /// </summary>
        internal static string DescriptionPredicateAssociationValidationGroup {
            get {
                return ResourceManager.GetString("DescriptionPredicateAssociationValidationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for relationship change sets..
        /// </summary>
        internal static string DescriptionRelationshipChangeSetStyle {
            get {
                return ResourceManager.GetString("DescriptionRelationshipChangeSetStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style sheet to be applied to Generic resource property control.
        /// </summary>
        internal static string DescriptionResourceCss {
            get {
                return ResourceManager.GetString("DescriptionResourceCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets title of related resources panel..
        /// </summary>
        internal static string DescriptionResourceDetailsViewRelatedResourcesTitle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailsViewRelatedResourcesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets edit resource association url..
        /// </summary>
        internal static string DescriptionResourceDetailViewEditResourceAssociationUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewEditResourceAssociationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets edit resource information url..
        /// </summary>
        internal static string DescriptionResourceDetailViewEditResourceInfoUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewEditResourceInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets RelatedResources panel style..
        /// </summary>
        internal static string DescriptionResourceDetailViewRelatedResourcesContainerStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewRelatedResourcesContainerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets RelatedResources header style..
        /// </summary>
        internal static string DescriptionResourceDetailViewRelatedResourcesHeaderStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewRelatedResourcesHeaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets RelatedResources item style..
        /// </summary>
        internal static string DescriptionResourceDetailViewRelatedResourcesItemStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewRelatedResourcesItemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets RelatedResources title style..
        /// </summary>
        internal static string DescriptionResourceDetailViewRelatedResourcesTitleStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewRelatedResourcesTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or set resource ID..
        /// </summary>
        internal static string DescriptionResourceDetailViewReourceId {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewReourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ResourceInfo panel style..
        /// </summary>
        internal static string DescriptionResourceDetailViewResourceInfoContainerStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewResourceInfoContainerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets title of Resource Info panel..
        /// </summary>
        internal static string DescriptionResourceDetailViewResourceInfoTitle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewResourceInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ResourceInfo title style..
        /// </summary>
        internal static string DescriptionResourceDetailViewResourceInfoTitleStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewResourceInfoTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets view change history url..
        /// </summary>
        internal static string DescriptionResourceDetailViewViewChangeHistoryUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewViewChangeHistoryUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets resource detail view url..
        /// </summary>
        internal static string DescriptionResourceDetailViewViewUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceDetailViewViewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to the alternate resource items..
        /// </summary>
        internal static string DescriptionResourceListViewAlternateItemStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewAlternateItemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to the buttons..
        /// </summary>
        internal static string DescriptionResourceListViewButtonStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to this control..
        /// </summary>
        internal static string DescriptionResourceListViewContainerStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewContainerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets data source..
        /// </summary>
        internal static string DescriptionResourceListViewDataSource {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets flag to enable or disable delete option..
        /// </summary>
        internal static string DescriptionResourceListViewEnableDeleteOption {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewEnableDeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to the All Items..
        /// </summary>
        internal static string DescriptionResourceListViewItemStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewItemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets current page index..
        /// </summary>
        internal static string DescriptionResourceListViewPageIndex {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets page size..
        /// </summary>
        internal static string DescriptionResourceListViewPageSize {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to the record separator..
        /// </summary>
        internal static string DescriptionResourceListViewSeparatorStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewSeparatorStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets visibility of footer.
        /// </summary>
        internal static string DescriptionResourceListViewShowFooter {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets visibility of header..
        /// </summary>
        internal static string DescriptionResourceListViewShowHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewShowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets sort direction..
        /// </summary>
        internal static string DescriptionResourceListViewSortDirection {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewSortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets sort expression..
        /// </summary>
        internal static string DescriptionResourceListViewSortExpression {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewSortExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets title of the control..
        /// </summary>
        internal static string DescriptionResourceListViewTitle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets style to be applied to the Title..
        /// </summary>
        internal static string DescriptionResourceListViewTitleStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets total records..
        /// </summary>
        internal static string DescriptionResourceListViewTotalRecords {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewTotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets view link url. Url format should be Url?Id={0}. {0} will be replaced by actual entity id..
        /// </summary>
        internal static string DescriptionResourceListViewViewUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceListViewViewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets resource type in Add mode.
        /// </summary>
        internal static string DescriptionResourceResourceType {
            get {
                return ResourceManager.GetString("DescriptionResourceResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets Authors column header..
        /// </summary>
        internal static string DescriptionResourceTableAuthorsHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceTableAuthorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets Contributor column header..
        /// </summary>
        internal static string DescriptionResourceTableContributorsHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceTableContributorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets DateAdded column header..
        /// </summary>
        internal static string DescriptionResourceTableDateAddedHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceTableDateAddedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Resource Filter..
        /// </summary>
        internal static string DescriptionResourceTableGetResourceBy {
            get {
                return ResourceManager.GetString("DescriptionResourceTableGetResourceBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get/set Title column header..
        /// </summary>
        internal static string DescriptionResourceTableTitleHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceTableTitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the url to be provided in Title column..
        /// </summary>
        internal static string DescriptionResourceTableTitleUrl {
            get {
                return ResourceManager.GetString("DescriptionResourceTableTitleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets Resource Type column header..
        /// </summary>
        internal static string DescriptionResourceTableTypeHeader {
            get {
                return ResourceManager.GetString("DescriptionResourceTableTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for resource tagging change sets..
        /// </summary>
        internal static string DescriptionResourceTaggingChangeSetStyle {
            get {
                return ResourceManager.GetString("DescriptionResourceTaggingChangeSetStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets file upload  control rendered with file resource type..
        /// </summary>
        internal static string DescriptionResourceUploadFileControl {
            get {
                return ResourceManager.GetString("DescriptionResourceUploadFileControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regular expression string for child regular expression validator.
        /// </summary>
        internal static string DescriptionResourceValidationCharsRegex {
            get {
                return ResourceManager.GetString("DescriptionResourceValidationCharsRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to determines on which validation group child validator will fire..
        /// </summary>
        internal static string DescriptionResourceValidationGroup {
            get {
                return ResourceManager.GetString("DescriptionResourceValidationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether child control validator are activated.
        /// </summary>
        internal static string DescriptionResourceValidationRequired {
            get {
                return ResourceManager.GetString("DescriptionResourceValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets resource authors link..
        /// </summary>
        internal static string DescriptionResourceViewAuthorsLink {
            get {
                return ResourceManager.GetString("DescriptionResourceViewAuthorsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets data source..
        /// </summary>
        internal static string DescriptionResourceViewDataSource {
            get {
                return ResourceManager.GetString("DescriptionResourceViewDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets resource files link..
        /// </summary>
        internal static string DescriptionResourceViewFilesLink {
            get {
                return ResourceManager.GetString("DescriptionResourceViewFilesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets resource title link..
        /// </summary>
        internal static string DescriptionResourceViewTitleLink {
            get {
                return ResourceManager.GetString("DescriptionResourceViewTitleLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for scalar properties change sets..
        /// </summary>
        internal static string DescriptionScalarPropertyChangeSetStyle {
            get {
                return ResourceManager.GetString("DescriptionScalarPropertyChangeSetStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the title of the control..
        /// </summary>
        internal static string DescriptionTableTitle {
            get {
                return ResourceManager.GetString("DescriptionTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets count of maximum tags to be displayed..
        /// </summary>
        internal static string DescriptionTagCloudMaxTagDisplayCount {
            get {
                return ResourceManager.GetString("DescriptionTagCloudMaxTagDisplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets navigation path..
        /// </summary>
        internal static string DescriptionTagCloudNavigationPath {
            get {
                return ResourceManager.GetString("DescriptionTagCloudNavigationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets ViewClicked event which is raised when user clicks on the link provided on Name column..
        /// </summary>
        internal static string DescriptionTagGridViewViewClicked {
            get {
                return ResourceManager.GetString("DescriptionTagGridViewViewClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Labels..
        /// </summary>
        internal static string DescriptionZentityButtonStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Controls..
        /// </summary>
        internal static string DescriptionZentityControlStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityControlStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result alternate row..
        /// </summary>
        internal static string DescriptionZentityGridViewAlternateStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewAlternateStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets of sets Columns to be displayed..
        /// </summary>
        internal static string DescriptionZentityGridViewDisplayColumns {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewDisplayColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets EditAssociation link url. Url format will change based on Entity Type. If EntityType is Tag/Category then Format is Url?Id={0}&amp;EntityType={1}.{0} will be replaced by actual entity id and {1} will be replaced by actual EntityType. If EntityType is Resource then Format is Url?Id={0}&amp;ResourceType={1}&amp;EntityType={2}. {0} will be replaced by actual entity id and {1} will be replaced by EntityType and {2} will be replaced by base type of EntityType..
        /// </summary>
        internal static string DescriptionZentityGridViewEditAssociationUrl {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewEditAssociationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets edit link url. Url format should be Url?Id={0}. {0} will be replaced by actual entity id..
        /// </summary>
        internal static string DescriptionZentityGridViewEditUrl {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewEditUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets flag to display or hide delete column..
        /// </summary>
        internal static string DescriptionZentityGridViewEnableDelete {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewEnableDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets Entity type..
        /// </summary>
        internal static string DescriptionZentityGridViewEntityType {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result footer row..
        /// </summary>
        internal static string DescriptionZentityGridViewFooterStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewFooterStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result header row..
        /// </summary>
        internal static string DescriptionZentityGridViewHeaderStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewHeaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result pager row..
        /// </summary>
        internal static string DescriptionZentityGridViewPagerRowStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewPagerRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result row..
        /// </summary>
        internal static string DescriptionZentityGridViewRowStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets title of search result grid..
        /// </summary>
        internal static string DescriptionZentityGridViewSearchResultTitleText {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewSearchResultTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for search result selected row..
        /// </summary>
        internal static string DescriptionZentityGridViewSelectedRowStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewSelectedRowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for title row..
        /// </summary>
        internal static string DescriptionZentityGridViewTitleStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets column name to have a view link..
        /// </summary>
        internal static string DescriptionZentityGridViewViewColumnName {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewViewColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets view link url. Url format should be Url?Id={0}. {0} will be replaced by actual entity id..
        /// </summary>
        internal static string DescriptionZentityGridViewViewUrl {
            get {
                return ResourceManager.GetString("DescriptionZentityGridViewViewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Labels..
        /// </summary>
        internal static string DescriptionZentityLabelStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityLabelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Alternate Item Row..
        /// </summary>
        internal static string DescriptionZentityTableAlternateItemStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityTableAlternateItemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Header Row..
        /// </summary>
        internal static string DescriptionZentityTableHeaderStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityTableHeaderStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for Item Row..
        /// </summary>
        internal static string DescriptionZentityTableItemStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityTableItemStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the maximum records to be fetched..
        /// </summary>
        internal static string DescriptionZentityTablePageSize {
            get {
                return ResourceManager.GetString("DescriptionZentityTablePageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Style defined for controls title..
        /// </summary>
        internal static string DescriptionZentityTableTitleStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityTableTitleStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get tree view node style.
        /// </summary>
        internal static string DescriptionZentityTreeViewNodeStyle {
            get {
                return ResourceManager.GetString("DescriptionZentityTreeViewNodeStyle", resourceCulture);
            }
        }
    }
}
