//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentity.Web.UI.Explorer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PublishingStatus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PublishingStatus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentity.Web.UI.Explorer.PublishingStatus", typeof(PublishingStatus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by user.
        /// </summary>
        internal static string AbortedByUser {
            get {
                return ResourceManager.GetString("AbortedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error – creation cancelled.
        /// </summary>
        internal static string AbortedOnError {
            get {
                return ResourceManager.GetString("AbortedOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Existing Collection.
        /// </summary>
        internal static string CopyingExistingCollection {
            get {
                return ResourceManager.GetString("CopyingExistingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying New Collection.
        /// </summary>
        internal static string CopyingNewCollection {
            get {
                return ResourceManager.GetString("CopyingNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DeepZoom Collection.
        /// </summary>
        internal static string CreatingDeepZoomCollection {
            get {
                return ResourceManager.GetString("CreatingDeepZoomCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating DeepZoom Images.
        /// </summary>
        internal static string CreatingDeepZoomImages {
            get {
                return ResourceManager.GetString("CreatingDeepZoomImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Images.
        /// </summary>
        internal static string CreatingImages {
            get {
                return ResourceManager.GetString("CreatingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Existing Collection.
        /// </summary>
        internal static string DeletingExistingCollection {
            get {
                return ResourceManager.GetString("DeletingExistingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Resource Items.
        /// </summary>
        internal static string FetchingResourceItems {
            get {
                return ResourceManager.GetString("FetchingResourceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiating.
        /// </summary>
        internal static string Initiating {
            get {
                return ResourceManager.GetString("Initiating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Started.
        /// </summary>
        internal static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Cleanup.
        /// </summary>
        internal static string PerformingCleanup {
            get {
                return ResourceManager.GetString("PerformingCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Resource Items.
        /// </summary>
        internal static string ProcessingResourceItems {
            get {
                return ResourceManager.GetString("ProcessingResourceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Intermediate Collection.
        /// </summary>
        internal static string PublishingIntermediateCollection {
            get {
                return ResourceManager.GetString("PublishingIntermediateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string Queued {
            get {
                return ResourceManager.GetString("Queued", resourceCulture);
            }
        }
    }
}
