// *******************************************************
//                                                        
//    Copyright (C) Microsoft. All rights reserved.       
//                                                        
// *******************************************************

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Zentity", Scope = "namespace", Target = "Zentity.Security.Authorization",
    Justification = "Zentity is the product name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Zentity",
    Justification = "Zentity is the product name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Portability", "CA1903:UseOnlyApiFromTargetedFramework",
    MessageId = "System.Data.Entity, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
    Justification = "The product supports .Net framework 3.5 and above only")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#",
    Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize(Zentity.Core.ZentityContext,System.String)",
    Justification = "The uri parameter is not a web site url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#",
    Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize(Zentity.Security.Authentication.AuthenticatedToken,Zentity.Core.ZentityContext,System.String)",
    Justification = "The uri parameter is not a web site url")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(!!0,Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(!!0,Zentity.Core.ZentityContext,System.String,Zentity.Security.Authentication.AuthenticatedToken)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(System.Data.Objects.ObjectQuery`1<!!0>,Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(System.Data.Objects.ObjectQuery`1<!!0>,Zentity.Core.ZentityContext,System.String,Zentity.Security.Authentication.AuthenticatedToken)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(System.Linq.IQueryable`1<!!0>,Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#Authorize`1(System.Linq.IQueryable`1<!!0>,Zentity.Core.ZentityContext,System.String,Zentity.Security.Authentication.AuthenticatedToken)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#GetAuthorizedResources`1(Zentity.Security.Authentication.AuthenticatedToken,Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Zentity.Security.Authorization.Group.#Identities",
    Justification = "The core data model generates navigation properties which are updatable")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#Groups")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#GetAuthorizedResources`1(Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#GrantAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#GrantAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#RevokeAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#RevokeAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#VerifyAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#VerifyAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#GetAuthorizedResources`1(Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#GrantAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#GrantAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#RevokeAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#RevokeAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#VerifyAuthorization(System.String,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#VerifyAuthorization`1(System.String,!!0,Zentity.Core.ZentityContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Zentity", Scope = "type", Target = "Zentity.Security.Authorization.SecureZentityContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.SecureZentityContext.#.ctor(System.Data.EntityClient.EntityConnection,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.SecureZentityContext.#.ctor(System.Data.EntityClient.EntityConnection,Zentity.Security.Authentication.AuthenticatedToken,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.SecureZentityContext.#.ctor(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.SecureZentityContext.#.ctor(System.String,Zentity.Security.Authentication.AuthenticatedToken,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Zentity.Security.Authorization.SecureZentityContext.#AuthorizingPredicateUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "2#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#GetAuthorizedResources(Zentity.Security.Authentication.AuthenticatedToken,Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.Group.#GetAuthorizedResources(Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.Identity.#GetAuthorizedResources(Zentity.Core.ZentityContext,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "1#", Scope = "member", Target = "Zentity.Security.Authorization.AuthorizationExtensions.#GetAuthorizedResources(Zentity.Core.ZentityContext,System.String)")]
